### ISSUE TITLE
Lecture 5 Example 5.3

### ISSUE THREAD

**Issue by bqi343** [csquires/6.S091-causality#1]
https://github.com/csquires/6.S091-causality/blob/main/lecture_notes/Lecture5.pdf

<img width="964" alt="Screen Shot 2023-01-25 at 12 14 12 PM" src="https://user-images.githubusercontent.com/21228024/214633774-48764e2a-5eac-430a-a0c5-f44784cd7da1.png">

I don't see why this example violates the intersection property. It doesn't satisfy the preconditions of the intersection property; in particular, $A\not\indep B_1|B_2$.

**Comment by csquires** [comment]
You're right - check the updated version of Lecture 5.

Side note - this is an example which violates *composition*, an additional property which takes us from graphoids to compositional graphoids.

**Comment by bqi343** [comment]
Lecture 5 hasn't been updated. (EDIT: Resolved, thanks!)
